import Link from "next/link";
import '../globals.css';
import { getPages } from "@/sanity/sanity-utils";

export const metadata = {
  title: 'Venkat Site',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pages = await getPages();
  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-20">
        <header className="flex items-center justify-between">
          <Link href='/'
          className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold"
          >
            Venkat
          </Link>

          <div className="flex items-center gap-5 text-sm text-white-600">
            {pages.map((page) => (
              <Link 
                key={page._id} 
                href={`/${page.slug}`}
                className='hover:text-violet-300'>
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-10">
          {children}
        </main>
        
      </body>
    </html>
  )
}
